[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@raphael/gamescope-stuff"
target = "/home/bluewy/.local/bin/gamescope-stuff"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@any/steam-stuff"
target = "/home/bluewy/.local/bin/steam-stuff"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@any/proton-stuff"
target = "/home/bluewy/.local/bin/proton-stuff"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/electron-any@any/electron-flags.conf"
target = "/home/bluewy/.config/electron-flags.conf"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/xkb-any@any"
target = "/home/bluewy/.config/xkb"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "/dev/null"
target = "/home/bluewy/.config/systemd/user/at-spi-dbus-bus.service"
