include = [
   "../#minimal/index.toml",

   "./files.toml",

   "../../../users-modules/for-bluewy/console-audio/files.toml",
   "../../../users-modules/for-bluewy/console-audio/packages.toml",
   "../../../users-modules/for-bluewy/console-other/packages.toml",
   "../../../users-modules/for-bluewy/gui-android/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-browse/files.toml",
   "../../../users-modules/for-bluewy/gui-apps-browse/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-comms/files.toml",
   "../../../users-modules/for-bluewy/gui-apps-comms/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-hardware/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-monitor/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-production/files.toml",
   "../../../users-modules/for-bluewy/gui-apps-production/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-reader/packages.toml",
   "../../../users-modules/for-bluewy/gui-apps-share/packages.toml",
   "../../../users-modules/for-bluewy/gui-fix/packages.toml",
   "../../../users-modules/for-bluewy/gui-gaming/files.toml",
   "../../../users-modules/for-bluewy/gui-gaming/packages.toml",
   "../../../users-modules/for-bluewy/gui-niri-base/files.toml",
   "../../../users-modules/for-bluewy/gui-niri-base/packages.toml",
   "../../../users-modules/for-bluewy/gui-niri-extra/files.toml",
   "../../../users-modules/for-bluewy/gui-niri-extra/packages.toml",
   "../../../users-modules/for-bluewy/gui-rice/packages.toml",
   "../../../users-modules/for-bluewy/gui-widgets/packages.toml",

   "./services.toml",
]
