[[files]]
source = '../../files/fuzzel-bluewy@raphael'
target = '/home/bluewy/.config/fuzzel'
action = 'link'
chmod = '751'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel']
