[[files]]
source = '../../files/kbd-root@raphael/colemak-dh-wide-custom-eu-iso.map'
target = '/usr/share/kbd/keymaps/colemak-dh-wide-custom-eu-iso.map'
action = 'copy'
chmod = '744'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']

[[files]]
source = '../../files/kbd-root@raphael/colemak-dh-wide-custom-eu-ansi.map'
target = '/usr/share/kbd/keymaps/colemak-dh-wide-custom-eu-ansi.map'
action = 'copy'
chmod = '744'
owner = 'root'
group = 'root'
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
