[[files]]
source = '../../files/nushell-bluewy@raphael'
target = '/home/bluewy/.config/nushell'
action = 'link'
chmod = '755'
owner = 'bluewy'
group = 'bluewy'
profiles = ['bluewy@raphael', 'bluewy@uriel', 'bluewy@sariel']

[[files]]
source = '../../files/nushell-bluewy@raphael'
target = '/home/yellowy/.config/nushell'
action = 'link'
chmod = '755'
owner = 'yellowy'
group = 'yellowy'
profiles = ['yellowy@uriel']
