[[files]]
source = '../../files/refind-root@raphael/refind.conf'
target = '/boot/EFI/refind/refind.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@raphael']

[[files]]
source = '../../files/refind-root@raphael/extra.conf'
target = '/boot/EFI/refind/extra.conf'
action = 'copy'
chmod = '644'
owner = 'root'
group = 'root'
profiles = ['root@raphael']
