packages = [
   { from = "std", name = "pipewire" },
   { from = "std", name = "pipewire-alsa" },
   { from = "std", name = "pipewire-pulse" },
   { from = "std", name = "pipewire-jack" },
   { from = "std", name = "wireplumber" },

   { from = "std", name = "plasma-meta" },
   { from = "std", name = "kde-applications-meta" },

   { from = "std", name = "cosmic-session" },

   { from = "std", name = "octopi" },
   { from = "std", name = "flatpak" },

   { from = "std", name = "profile-sync-daemon" },
   { from = "std", name = "cachyos-firefox-settings" },
   { from = "aur", name = "equibop-bin" },
]
