packages = [
   # [ gui.gaming ]
   #
   { from = "aur", name = "atlauncher-bin", ignore = true },
   { from = "aur", name = "r2modman-bin", ignore = true },
   { from = "aur", name = "osu-lazer-bin", ignore = true },
   { from = "aur", name = "bettercrewlink-bin", ignore = true },
   { from = "std", name = "steam-native-runtime" },
   { from = "std", name = "heroic-games-launcher-bin" },

   { from = "std", name = "umu-launcher" },
   { from = "std", name = "proton-cachyos" },
   { from = "std", name = "proton-ge-custom-bin" },
   { from = "std", name = "protontricks" },
   { from = "std", name = "gamescope" },
   { from = "std", name = "mangohud" },
]
