[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@belphegor/refind.conf"
target = "/boot/efi/refind/refind.conf"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@belphegor/extra.conf"
target = "/boot/efi/refind/extra.conf"
