packages = [
   # [ gui.apps.reader ]
   #
   { from = "std", name = "nautilus" },
   { from = "std", name = "gvfs" },
   { from = "std", name = "gvfs-afc" },
   { from = "std", name = "gvfs-dnssd" },
   { from = "std", name = "gvfs-mtp" },
   { from = "std", name = "gvfs-nfs" },
   { from = "std", name = "gvfs-smb" },
   { from = "std", name = "gvfs-wsdd" },
   { from = "std", name = "vlc" },
   { from = "std", name = "vlc-plugins-all" },
   { from = "std", name = "loupe" },
   { from = "std", name = "evince" },
]
