[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/nushell-any@any"
target = "/home/bluewy/.config/nushell"

[[items-install]]
group = "bluewy"
operation = "copy"
owner = "bluewy"
source = "../../../files/user-dirs-any@any/user-dirs.dirs"
target = "/home/bluewy/.config/user-dirs.dirs"
