[[items-install]]
group = "bluewy"
operation = "copy"
owner = "bluewy"
source = "../../../files/user-dirs-any@any/user-dirs.dirs"
target = "/home/bluewy/.config/user-dirs.dirs"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "/dev/null"
target = "/home/bluewy/.config/systemd/user/xdg-user-dirs.service"
