[[packages]]
install = [
   { from = 'lcl', name = 'nushell-custom', path = '../../../../aur/nushell-custom' },
   # already pulled by nushell-custom, though it is here just in case the above
   # fails (unlikely)
   { from = 'std', name = 'nushell' },
   { from = 'std', name = 'terminus-font' },
   { from = 'std', name = 'fastfetch' },
   { from = 'std', name = 'starship' },

   { from = 'std', name = 'zellij' },

   { from = 'std', name = 'flatpak' },
   { from = 'std', name = 'paru' },
   { from = 'std', name = 'downgrade' },

   { from = 'lcl', name = 'sam-git', path = '../../../../aur/sam-git' },
]
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
