[[packages]]
install = [
   { from = 'std', name = 'bottom' },
   { from = 'std', name = 'bandwhich' },
   { from = 'std', name = 'nvtop' },
]
profiles = ['root@raphael', 'root@uriel', 'root@sariel', 'root@belphegor']
