[[packages]]
install = [
   { from = 'std', name = 'uwsm' },

   { from = 'std', name = 'niri' },
   { from = 'std', name = 'xwayland-satellite' },
   { from = 'std', name = 'xdg-desktop-portal-gnome' },
   { from = 'std', name = 'xdg-desktop-portal-gtk' },

   { from = 'aur', name = 'wezterm-git' },
   { from = 'std', name = 'libgit2' },

   { from = 'std', name = 'pantheon-polkit-agent' },

   { from = 'std', name = 'hypridle' },
   { from = 'std', name = 'wayland-pipewire-idle-inhibit' },

   { from = 'std', name = 'cliphist' },
   { from = 'std', name = 'cava' },
   { from = 'std', name = 'noctalia-shell' },
   { from = 'std', name = 'satty' },

   { from = 'std', name = 'keepassxc' },
]
profiles = ['root@raphael', 'root@uriel']
