[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@raphael/refind.conf"
target = "/boot/efi/refind/refind.conf"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@raphael/extra.conf"
target = "/boot/efi/refind/extra.conf"

[[spawn_files]]
content = """
[Match]
Name=eno1

[Network]
DHCP=yes

[DHCPv4]
RouteMetric=100

[IPv6AcceptRA]
RouteMetric=100
"""
group = "root"
owner = "root"
target = "/etc/systemd/network/20-wired.network"

[[spawn_files]]
content = """
[Match]
Name=wlan0

[Network]
DHCP=yes

[DHCPv4]
RouteMetric=600

[IPv6AcceptRA]
RouteMetric=600
"""
group = "root"
owner = "root"
target = "/etc/systemd/network/21-wireless.network"

[[spawn_files]]
content = """
[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
"""
group = "root"
owner = "root"
target = "/etc/resolved.conf"
