[[units]]
enable = [
   "getty@tty1.service",

   "systemd-networkd.service",
   "systemd-network-generator.service",
   "systemd-networkd-wait-online.service",
   "systemd-resolved.service",
   "iwd.service",

   "systemd-timesyncd.service",

   "lactd.service",
]
path = "/etc/systemd/system"
user = "root"
