[[items-install]]
group = "yellowy"
operation = "link"
owner = "yellowy"
source = "../../../files/fastfetch-any@any"
target = "/home/yellowy/.config/fastfetch"

[[items-install]]
group = "yellowy"
operation = "link"
owner = "yellowy"
source = "../../../files/nushell-any@any"
target = "/home/yellowy/.config/nushell"

[[items-install]]
group = "yellowy"
operation = "link"
owner = "yellowy"
source = "../../../files/nvim-any@any"
target = "/home/yellowy/.config/nvim"

[[items-install]]
group = "yellowy"
operation = "link"
owner = "yellowy"
source = "../../../files/starship-any@any/starship.toml"
target = "/home/yellowy/.config/starship.toml"

[[items-install]]
group = "yellowy"
operation = "copy"
owner = "yellowy"
source = "../../../files/user-dirs-any@any/user-dirs.dirs"
target = "/home/yellowy/.config/user-dirs.dirs"
