[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@uriel/refind.conf"
target = "/boot/efi/Microsoft/Boot/refind.conf"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/refind-any@uriel/extra.conf"
target = "/boot/efi/Microsoft/Boot/extra.conf"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/acer-battery-limiter.service"
target = "/etc/systemd/system/acer-battery-limiter.service"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/acer-battery-limit-service-any@uriel/limit-acer-battery"
target = "/usr/local/bin/limit-acer-battery"

[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../files/libinput-any@any/local-overrides.quirks"
target = "/etc/libinput/local-overrides.quirks"
