include = [
   "./files.toml",
   "./packages.toml",
   "./services.toml",

   "../../hosts-modules/for-bluewy/system/files.toml",
   "../../hosts-modules/for-bluewy/system/packages.toml",
   "../../hosts-modules/for-bluewy/system/services.toml",
   "../../hosts-modules/for-bluewy/locale-iso/files.toml",
   "../../hosts-modules/for-bluewy/locale-iso/packages.toml",
   "../../hosts-modules/for-bluewy/systemd-xdg-autostart-generator-disable/files.toml",
   "../../hosts-modules/for-bluewy/wireless-regdb-es-region/files.toml",
   "../../hosts-modules/for-bluewy/wireless-regdb-es-region/packages.toml",
   "../../hosts-modules/for-bluewy/networkmanager/files.toml",
   "../../hosts-modules/for-bluewy/networkmanager/packages.toml",
   "../../hosts-modules/for-bluewy/networkmanager/services.toml",
   "../../hosts-modules/for-bluewy/bluetooth/packages.toml",
   "../../hosts-modules/for-bluewy/bluetooth/services.toml",
   "../../hosts-modules/for-bluewy/rtcwake-for-mc-server-#gpu-nvidia/files.toml",
   "../../hosts-modules/for-bluewy/rtcwake-for-mc-server-#gpu-nvidia/services.toml",

   "../../users/bluewy/@uriel/index.toml",
   "../../users/yellowy/#server/index.toml",
   "../../users/elisa/@any/index.toml",
]
