[[items-install]]
group = "root"
operation = "copy"
owner = "root"
source = "../../../files/bin-any@any/nu-custom"
target = "/usr/bin/nu-custom"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/nushell-any@any"
target = "/home/bluewy/.config/nushell"
