packages = [
   # [ console.neovim ]
   #
   { from = "std", name = "neovim" },

   { from = "std", name = "ripgrep" },
   { from = "std", name = "fzf" },

   { from = "std", name = "rust-analyzer" },

   { from = "std", name = "eslint_d" },

   { from = "std", name = "prettier" },
   { from = "std", name = "stylua" },
   { from = "std", name = "taplo-cli" },
]
