[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/niri-custom-service-any@any/niri-custom.service"
target = "/home/bluewy/.config/systemd/user/niri-custom.service"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/bin-any@any/niri-custom-session"
target = "/home/bluewy/.local/bin/niri-custom-session"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/hypr-any@raphael"
target = "/home/bluewy/.config/hypr"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/fuzzel-any@any"
target = "/home/bluewy/.config/fuzzel"

[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/wezterm-any@any"
target = "/home/bluewy/.config/wezterm"

[[files-spawn]]
content = """
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/keepassxc
"""
group = "bluewy"
owner = "bluewy"
target = "/home/bluewy/.local/share/dbus-1/services/org.freedesktop.secrets.service"
