[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/niri-custom-service-any@any/niri-custom.service"
target = "/home/bluewy/.config/systemd/user/niri-custom.service"
