[[items-install]]
group = "bluewy"
operation = "link"
owner = "bluewy"
source = "../../../files/logind-any@raphael/frequency.conf"
target = "/home/bluewy/.config/systemd/user/psd-resync.timer.d/frequency.conf"
